version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: courses
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5433:5432
